[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Configure secrets scanner to allow reCAPTCHA site key in client bundle
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_RECAPTCHA_SITE_KEY,RECAPTCHA_SITE_KEY"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"